### ISSUE TITLE
"Checking route..."

### ISSUE THREAD

**Issue by Liriy** [Flowseal/zapret-discord-youtube#302]
конечно сижу на arch linux, но пытался конфиг из батника скопировать настолько хорошо, на сколько мог
да и на винде тоже самое :shrug:

**Comment by 4toyota2supra** [comment]
пофиксил через кастомный скрипт на линуксе, а на винде стал пользоватся амнезией с конфигом

**Comment by prohakartoha** [comment]
> пофиксил через кастомный скрипт на линуксе, а на винде стал пользоватся амнезией с конфигом

Ну так что работает? Мне очень нужен дискорд.

**Comment by 4toyota2supra** [comment]
работают оба, и на Линукс, и на Windows через конфиг Flowseal22:05, 8 февраля 2025 г., "YT_ProhaKartoha" ***@***.***>:

пофиксил через кастомный скрипт на линуксе, а на винде стал пользоватся амнезией с конфигом

Ну так что работает? Мне очень нужен дискорд.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты
